apiVersion: v2
name: metadataservice
description: Metadata Service - the successor to Kant
type: application
version: 0.1.0
appVersion: "1.0"
sources:
  - https://github.com/metal-toolbox/hollow-metadataservice
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.16.1
