metadataservice:
  image:
    repository: ghcr.io/metal-toolbox/hollow-metadataservice
    tag: "v0.0.3"

ingress:
  enabled: true
  hostnames:
    - metadata-service.mydomain
  publicPaths:
    - $
    - metadata
    - userdata
    - '2009-04-04'

oidc:
  audience: ""
  issuer: ""
  jwksuri: ""
  rolesClaim: ""
  userClaim: ""

lookup:
  enabled: false

  serviceURL: ""
  serviceURLFrom: {}

  oidc:
    issuer: ""
    clientID: ""
    clientSecret: ""
    audience: ""
    scopes: [] # may also be a comma or space separated string
      # - scope-one
      # - scope-two

    # # Source the variables value. See env.valueFrom for supported values
    # # Value from *From is preferred over the string variable
    # issuerFrom: {}
    # clientIDFrom:
    #   secretKeyRef:
    #     name: lookup-oidc
    #     key: client-id
    # clientSecretFrom:
    #   secretKeyRef:
    #     name: lookup-oidc
    #     key: client-secret
    # audienceFrom: {}
    # # scopes should be formatted as white space separated strings
    # scopesFrom: {}

replicaCount: 1
resources:
  limits:
    cpu: 4
    memory: 4Gi
  requests:
    cpu: 4
    memory: 4Gi
