metadataservice:
  image:
    repository: ghcr.io/metal-toolbox/hollow-metadataservice
    tag: "v0.0.1"
  env:
    DEBUG: "true"
  publicPaths:
    - $
    - metadata
    - userdata
    - components
    - '2009-04-04'
