apiVersion: v1
kind: Service
metadata:
  name: metadata-service
  labels:
    k8s-app: metadata-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9090
  - name: https
    port: 443
    protocol: TCP
    targetPort: 9090
  selector:
    k8s-app: metadata-service
