apiVersion: v1
kind: Service
metadata:
  name: metadata-service
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8000
  selector:
    k8s-app: metadata-service
